### PR TITLE
feat(device): initial CSI driver for device

### PR DESCRIPTION
**Pull request by pawanpraka1**
Signed-off-by: Pawan <pawan@mayadata.io>

### CODE REVIEW

**Comment by praveengt** [comment]
Why docker push is failing

**Comment by praveengt** [comment]
I think we can merge this and fix any issues when it comes to testing

**Comment by pawanpraka1** [comment]
> Why docker push is failing

it is failing because docker credentials are not set for this repo.

**Review by prateekpandey14 — APPROVED** [review]
lgtm for now, in upcoming PR we can bump the k8s and client-go version to atleast 1.20.

**Pull request merged**
